version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
      - image: registry:2
        name: registry
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Installing test/lint dependencies
          command: |
            # get python3 for tox
            apt-get update
            apt-get install -yq --no-install-recommends --fix-missing \
                curl \
                git \
                make \
                python \
                python-dev \
                python-pip \
                python-setuptools \
                python3 \
                python3-dev \
                python3-pip \
                python3-setuptools \
                python3-wheel \
                tar
            python3 -m pip install tox

      - run:
          name: lint tests
          command: |
            make lint

      - run:
          name: Run unit tests
          command: |
            make test

      - run:
          name: Run make dist and test the wheels and versions
          command: |
            make dist
            SHORT_HASH=$(git rev-parse --short HEAD)
            MLT_DIST_WHEEL="mlt*${SHORT_HASH}*-py2.py3-none-any.whl"
            ls dist/${MLT_DIST_WHEEL}
            if [[ $? != 0 ]]; then
                exit 1
            fi
            pip install --no-cache-dir pip==9.0.1
            PIP=/usr/local/bin/pip
            $PIP install -I dist/${MLT_DIST_WHEEL}
            PIP_DEPS=$(${PIP} freeze)
            if [[ $PIP_DEPS != *"mlt=="*"${SHORT_HASH}"* ]]; then
                exit 1
            fi
            . .venv/bin/activate
            MLT_VERSION=$(mlt --version)
            if [[ $MLT_VERSION != *"${SHORT_HASH}"* ]]; then
                exit 1
            fi
            deactivate

      - run:
          name: Installing docker dependencies
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            curl -L https://github.com/docker/compose/releases/download/1.16.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Run e2e tests
          command: |
            make test-e2e
